<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ApplicationCountNumber</name>
   <tag></tag>
   <elementGuidId>121eb945-3983-42ad-8486-9bd324527fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Applications-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
