<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ApplicationName</name>
   <tag></tag>
   <elementGuidId>a8149508-8435-4406-ae96-63f3606717e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Applications-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
