<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusHourAnomaliesCountNumber</name>
   <tag></tag>
   <elementGuidId>f4a456a1-8743-4696-a77a-de7684d5c4c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Bus\._Hrs_Anomalies-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
