<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusHourAnomaliesName</name>
   <tag></tag>
   <elementGuidId>a6c0faa2-4d79-4fc1-83d7-b309bbeeb1d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Bus\._Hrs_Anomalies-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
