<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AuthFailureCountNumber</name>
   <tag></tag>
   <elementGuidId>46d556fe-a9ce-406a-b059-d9dba45ebfea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Auth_Failures-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
