<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AuthFailureName</name>
   <tag></tag>
   <elementGuidId>d7c97358-6f43-431a-833e-a3d9dbe8c83a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Auth_Failures-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
