<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserCountNumber</name>
   <tag></tag>
   <elementGuidId>1c969933-a78f-4d92-a958-af4afdbb83ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Users-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
