<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DevicesCountNumber</name>
   <tag></tag>
   <elementGuidId>0842a86c-4b1d-4df7-93c9-3436ff3ef8c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Devices-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
