<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DevicesName</name>
   <tag></tag>
   <elementGuidId>fa599a5b-df55-4ce5-b8eb-77e4cdf6649c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Devices-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
