<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GatewaysCountNumber</name>
   <tag></tag>
   <elementGuidId>2dc273c0-4777-41d5-b8e1-a9dd00892898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Gateways-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
