<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GatewaysName</name>
   <tag></tag>
   <elementGuidId>67fa43b3-0d05-4ea9-8eda-3cc6a2b2ed12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Gateways-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
