<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AuthFailureName</name>
   <tag></tag>
   <elementGuidId>dd51b775-9be5-4ef5-a2d3-f1ea672e5a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Auth_Failures-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
