<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AuthFailureCountNumber</name>
   <tag></tag>
   <elementGuidId>604f715d-a308-45ef-bd03-0074817d9612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Auth_Failures-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
