<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-complianceName</name>
   <tag></tag>
   <elementGuidId>c14a9217-4b43-4923-8c31-8dcab1071b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Non_Compliance-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
