<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-complianceCountNumber</name>
   <tag></tag>
   <elementGuidId>112c4eba-ca27-40c6-bd99-42eec48264b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Non_Compliance-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
