<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GatewaysName</name>
   <tag></tag>
   <elementGuidId>471ef711-bc6a-4195-9cf6-ff8d0e48f13a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Gateways-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
