<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GatewaysCountNumber</name>
   <tag></tag>
   <elementGuidId>5d264387-92e3-4e5f-a1c6-3ab7e4c03e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Gateways-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
