<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Geo-anomaliesCountNumber</name>
   <tag></tag>
   <elementGuidId>7c1e7a27-0426-4830-b745-dea8c7b219a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Geo_Location_Anomalies-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
