<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Geo-anomaliesName</name>
   <tag></tag>
   <elementGuidId>2e22f302-7921-4a34-bf28-6244517d0172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Geo_Location_Anomalies-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
