<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusHourAnomaliesName</name>
   <tag></tag>
   <elementGuidId>2d4fb84f-ce55-4210-96ec-bf44ef3293d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Business_Hour_Anomalies-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
