<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusHourAnomaliesCountNumber</name>
   <tag></tag>
   <elementGuidId>90dcfde2-3ee4-482f-94e9-3196117cf0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Business_Hour_Anomalies-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
