<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Geo-anomaliesCountNumber</name>
   <tag></tag>
   <elementGuidId>ba97bd00-06e5-49bf-8df3-8f515be5db57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Geo_Anomalies-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
