<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Geo-anomaliesName</name>
   <tag></tag>
   <elementGuidId>786390d3-5e3d-4d56-9672-d655f0155770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Geo_Anomalies-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
