<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-complianceName</name>
   <tag></tag>
   <elementGuidId>f1e44dcb-a113-4d3b-ad25-8db67f394877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Non_Compliance-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
