<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-complianceCountNumber</name>
   <tag></tag>
   <elementGuidId>ce62dd48-2119-4895-8fb4-46f481184a34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Non_Compliance-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
