<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-complianceCountNumber</name>
   <tag></tag>
   <elementGuidId>0274575e-5c56-41ef-994d-200fe16b20b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Non-Compliant_Devices-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
