<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-complianceName</name>
   <tag></tag>
   <elementGuidId>46e58a58-4548-41cb-8039-1f5f1f5647b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Non-Compliant_Devices-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
