<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AnomaliesName</name>
   <tag></tag>
   <elementGuidId>7d409556-c7e5-49df-9dda-667e458c9c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Anomalies-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
