<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AnomaliesCountNumber</name>
   <tag></tag>
   <elementGuidId>a8257637-c5c8-481b-a9b3-093658fe4762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Anomalies-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
