<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserCountNumber</name>
   <tag></tag>
   <elementGuidId>39d65a12-4cfa-4683-8316-b1c3d7b4ab0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Users-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
