<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ApplicationCountNumber</name>
   <tag></tag>
   <elementGuidId>fe4bc48e-5ab8-4002-b12e-b08dd3f801a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Applications-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
