<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ApplicationName</name>
   <tag></tag>
   <elementGuidId>c5df3139-e109-464b-b448-28eb8cdce465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Applications-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
