<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DevicesName</name>
   <tag></tag>
   <elementGuidId>7fa09018-9d51-4914-919e-286073ff2d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Devices-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
