<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DevicesCountNumber</name>
   <tag></tag>
   <elementGuidId>a0955416-8bff-463c-9ee4-c696e0dacfdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Devices-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
